name: Build and Deploy
on:
  push:
    branches:
      - master
      - ci/action

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install
        run: yarn --immutable
      - name: Build
        run: yarn release
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist/docs/browser
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
